# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Sandeep'
        # Input has to be provided for the workflow to run
        required: true
      place:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Place'
        # Default value if no value is explicitly provided
        default: 'India'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Command run
      run: |
        set +e
        echo "Running wrong command"
        lt
    - name: Create workflow
      id: execute-test
      run: |
        Status="$?"
        echo "********Status********"
        if [Status -eq 0] then
          curl --request POST 'https://api.github.com/repos/Sandeep89sharma/JagerTracing/actions/workflows/manual.yml/dispatches' \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer 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' \
          --data-raw '{"ref":"master",
          "inputs":{"name":"Mona the Octocat"}
          }'
        fi
